yarnPath: .yarn/releases/yarn-3.1.1.cjs
nodeLinker: node-modules
packageExtensions:
  "@docusaurus/lqip-loader@*":
    dependencies:
      "webpack": "5.*"
  "@docusaurus/plugin-ideal-image@*":
    dependencies:
      "prop-types": "*"
  "@docusaurus/plugin-pwa@*":
    dependencies: 
      "prism-react-renderer": "*"
  "@docusaurus/theme-search-algolia@*":
    dependencies: 
      "prism-react-renderer": "*"
  "@docusaurus/preset-classic@*":
    dependencies:
      "prism-react-renderer": "*"  
  "@docusaurus/utils-validation@*":
    dependencies:
      "react": "16.14.0"
      "react-dom": "16.14.0"
  "@docusaurus/core@*":
    dependencies:
      "typescript": "*"
  "theme-ui@*":
    dependencies:
      "react": "16.14.0"
  "react-dev-utils@*":
    dependencies:
      "webpack": "*"
      "typescript": "*"
